
msg: sri rama notes
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console:
      path: /h2-console
  boot:
    admin:
      client:
        url: http://localhost:1111

springdoc:
  api-docs:
    path: /api-docs


management:
  endpoints:
    web:
      exposure:
        include: '*' 
