spring:
  application:
    name: Notes-Microservice
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console:
      path: /h2-console
  boot:
    admin:
      client:
        url: http://localhost:1111
  zipkin:
   base-url: http://localhost:9411/
   enabled: true
   service.name: NOTES-MICROSERVICE
   sender.type: web
  sleuth:
    sampler:
      probability: 1.0
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
server:
  port : 9090
  servlet:
    context-path: /notesService

management:
  endpoints:
    web:
      exposure:
        include: '*' 