
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  boot:
    admin:
      client:
        url: http://localhost:1111/
msg: Hello World
management:
  endpoints:
    web:
      exposure:
        include: '*'
